# Generated by Django 4.0 on 2022-03-25 07:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('password', models.CharField(max_length=15)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144)),
                ('desc', models.TextField(blank=True, default='', verbose_name='description')),
                ('url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('only_one', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift', to='gift_registry.group')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Gifter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_registry.gift')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('gift', 'name')},
            },
        ),
    ]
