# Generated by Django 4.0 on 2022-03-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='password',
            new_name='join_code',
        ),
    ]
