# Generated by Django 4.0 on 2022-03-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry', '0003_alter_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='join_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
