# Generated by Django 4.0 on 2022-03-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry', '0007_alter_group_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_registry.group'),
        ),
    ]
