# Generated by Django 4.0 on 2022-03-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry', '0008_alter_gift_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='url',
            field=models.URLField(),
        ),
    ]
