# Generated by Django 4.0 on 2022-03-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry', '0009_alter_gift_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='reciever',
            field=models.CharField(default='', max_length=50),
        ),
    ]
