# Generated by Django 4.0 on 2022-04-01 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry', '0010_gift_reciever'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gifter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gifter',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gift_registry.group'),
        ),
        migrations.AlterField(
            model_name='gifter',
            name='gift',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gift_registry.gift'),
        ),
        migrations.AlterUniqueTogether(
            name='gifter',
            unique_together={('group', 'name')},
        ),
    ]
