# Generated by Django 4.0 on 2022-04-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry', '0012_gift_claimed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gifter',
            options={'ordering': ['group']},
        ),
        migrations.AlterUniqueTogether(
            name='gifter',
            unique_together=set(),
        ),
    ]
