# Generated by Django 4.0 on 2022-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry', '0013_alter_gifter_options_alter_gifter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
